#!/usr/bin/php
<?php

include './XpscounterClass.php';

$counter = new Xpscounter("./conf.json");
$counter->setupAll();
$counter->countMyXps();
if ($argc == 2 && $argv[1] == "--details") {
    $counter->printAll();
} else {
    $counter->print();
}

?>